/*
 * Swagger Test Game - OpenAPI 3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.11
 * Contact: srgkharkov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Config struct {
	Id *Object `json:"id,omitempty"`

	Name *Object `json:"name"`

	Type_ *Object `json:"type"`

	JSON *Object `json:"JSON"`
}
